export interface Fall2026Course {
  code: string;
  title: string;
  credit: string;
  theory: number;
  lab: number;
  prerequisite: string;
  programs: string[];
}

export const OFFICIAL_FALL_2026_COURSES: Fall2026Course[] = [
  // BSCS Core & Electives
  { code: "CSC101", title: "Applications of Information and Communication Technologies", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM104", title: "Functional English", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM112", title: "Islamic Studies", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM113", title: "Ideology and Constitution of Pakistan", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM116", title: "Ethics", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM117", title: "Pakistan Studies", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM120", title: "Expository Writing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM161", title: "Understanding of Holy Quran - I", credit: "1(0,1)", theory: 0, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM162", title: "Understanding of Holy Quran - II", credit: "1(0,1)", theory: 0, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM208", title: "Civics and Community Engagement", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "MGT250", title: "Introduction to Entrepreneurship", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "MTH103", title: "Exploring Quantitative Skills", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "MTH114", title: "Tools for Quantitative Reasoning", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CSC102", title: "Discrete Structures", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CSC103", title: "Programming Fundamentals", credit: "4(3,1)", theory: 3, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CSC211", title: "Data Structures", credit: "4(3,1)", theory: 3, lab: 1, prerequisite: "CSC103", programs: ["BSCS", "BSSE"] },
  { code: "CSC232", title: "Information Security", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CSC241", title: "Object Oriented Programming", credit: "4(3,1)", theory: 3, lab: 1, prerequisite: "CSC103", programs: ["BSCS", "BSSE"] },
  { code: "CSC262", title: "Artificial Intelligence", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CSC270", title: "Database Systems", credit: "4(3,1)", theory: 3, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CSC275", title: "Computer Networks", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CSC291", title: "Software Engineering", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CSC301", title: "Design and Analysis of Algorithms", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "CSC211", programs: ["BSCS", "BSSE"] },
  { code: "CSC312", title: "Theory of Automata", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CSC319", title: "Cloud Computing", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "CSC324", title: "Operating System Principles", credit: "4(3,1)", theory: 3, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "CSC323", title: "Operating Systems", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSSE"] },
  { code: "CSC325", title: "Computer Organization and Assembly Language", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "EEE241", programs: ["BSCS", "BSSE"] },
  { code: "EEE241", title: "Digital Logic Design", credit: "4(3,1)", theory: 3, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "EEE240", title: "Fundamentals of Digital Logic Design", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSSE"] },
  { code: "CSC395", title: "Internship", credit: "3(0,3)", theory: 0, lab: 3, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CSC410", title: "Professional Practices for IT", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CSC375", title: "Professional Certification", credit: "3(0,3)", theory: 0, lab: 3, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CSC498", title: "Final Year Project I", credit: "2(0,2)", theory: 0, lab: 2, prerequisite: "CSC241, CSC270, CSC291", programs: ["BSCS"] },
  { code: "CSC499", title: "Final Year Project II", credit: "4(0,4)", theory: 0, lab: 4, prerequisite: "CSC498", programs: ["BSCS"] },
  { code: "CSE498", title: "Final Year Project I", credit: "2(0,2)", theory: 0, lab: 2, prerequisite: "CSC241, CSC262, CSC270, CSC291", programs: ["BSSE"] },
  { code: "CSE499", title: "Final Year Project II", credit: "4(0,4)", theory: 0, lab: 4, prerequisite: "CSE498", programs: ["BSSE"] },
  { code: "MTH091", title: "Pre-Calculus I (deficiency, pre-med only)", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "MTH092", title: "Pre-Calculus II (deficiency, pre-med only)", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "DEV342", title: "Local Government System and Rural Development", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "ECO212", title: "Economics of Pakistan", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "ECO484", title: "Project Planning and Monitoring", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "FIN485", title: "Technology in Finance", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM220", title: "Introduction to Psychology", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM221", title: "International Relations", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "HUM430", title: "French", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM431", title: "German", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM432", title: "Arabic", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM434", title: "Chinese", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "MET205", title: "Geographic Information System", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "MET317", title: "Geospatial Databases", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "MET411", title: "Spatial Data Analysis and Modeling", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "MGT131", title: "Financial Accounting", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "MGT210", title: "Fundamentals of Marketing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "MGT350", title: "Human Resource Management", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "MGT513", title: "New Product Development", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "MTH104", title: "Calculus and Analytic Geometry", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "MTH231", title: "Linear Algebra", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "MTH240", title: "Introduction to Scientific Computing", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "MTH262", title: "Statistics and Probability Theory", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM107", title: "21st Century Communication Skills", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM123", title: "Fundamentals of Philosophy", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "ADA111", title: "History and Theory of Art and Culture I", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "ARC108", title: "Art Appreciation", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "ARC351", title: "Calligraphic Arts", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSSE"] },
  { code: "HUM310", title: "Islamic History", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "BIO100", title: "Fundamentals of Biology", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "BIO310", title: "Introduction to Bioinformatics", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "BIO321", title: "Fundamentals of Genetics", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CHM100", title: "Introduction to Chemistry", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "PHY124", title: "Applied Physics", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM122", title: "Fundamentals of Psychology", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM130", title: "Fundamentals of Sociology", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM131", title: "Anthropology", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM209", title: "Fundamentals of Political Science", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM222", title: "Fundamentals of International Relations", credit: "2(2,0)", theory: 2, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "HUM121", title: "Technical and Business Writing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSSE"] },
  { code: "MTH105", title: "Multivariable Calculus", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSSE"] },

  // Electives
  { code: "AIC270", title: "Programming for Artificial Intelligence", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSC262", programs: ["BSCS"] },
  { code: "AIC329", title: "Multi-agent Systems", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "AIC337", title: "Agentic AI", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "AIC341", title: "Introduction to Computer Vision", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "AIC345", title: "Generative AI", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "AIC350", title: "Topics in Artificial Intelligence I", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "AIC354", title: "Machine Learning Fundamentals", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "AIC355", title: "Machine Learning Operations (MLOps)", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "AIC357", title: "Responsible AI", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "AIC365", title: "Natural Language Processing", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "AIC368", title: "Optimization Techniques", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "AIC369", title: "Stochastic Processes", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "AIC372", title: "Knowledge Representation and Reasoning", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "CSC262", programs: ["BSCS"] },
  { code: "AIC378", title: "Speech Processing", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "AIC380", title: "Artificial Neural Networks and Deep Learning", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSC262", programs: ["BSCS"] },
  { code: "AIC456", title: "Reinforcement Learning", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "AIC469", title: "Evolutionary Computing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "AIC483", title: "Topics in Artificial Intelligence II", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "DSC306", title: "Data Mining", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },

  { code: "CYC205", title: "Introduction to Cyber Security", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC207", title: "Information Security Management", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC210", title: "Digital Forensics and Incident Response", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC215", title: "Data Center Security", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC230", title: "Mathematical Foundations for Cryptography", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC232", title: "Symmetric Key Cryptography", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC312", title: "Cyber Threat Intelligence", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC315", title: "Computer Forensics", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC317", title: "Smart Devices and IoT Forensics", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC318", title: "Information Privacy and Security", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC320", title: "Asymmetric Key Cryptography", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC331", title: "Cryptography", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC340", title: "Cryptanalysis and Attack Techniques", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC350", title: "Topics in Cyber Security I", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC365", title: "Network Security", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSC275", programs: ["BSCS"] },
  { code: "CYC370", title: "Machine Learning for Network Security", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC372", title: "Network and System Administration", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC373", title: "Network Forensics", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC386", title: "Secure Software Design and Development", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC395", title: "Vulnerability Assessment and Penetration Testing", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC400", title: "Cryptographic Hash Functions and Blockchain Applications", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC403", title: "Cloud and Application Security", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC405", title: "Cloud Security", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC407", title: "Cloud Forensics and Log Analysis", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC410", title: "Open Source Intelligence Techniques", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC412", title: "Incident Response Orchestration and Automation", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC460", title: "Malware Analysis and Reverse Engineering", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC465", title: "Security Automation for Network Operations", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC467", title: "Mobile and Wireless Network Security", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CYC483", title: "Topics in Cyber Security II", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },

  { code: "DSC293", title: "Data Science Fundamentals", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "DSC295", title: "Data Engineering", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "DSC300", title: "Statistical Methods in Data Science", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "MTH262", programs: ["BSCS"] },
  { code: "DSC303", title: "Tools and Techniques in Data Science", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "DSC309", title: "Data Science Design Patterns", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "DSC327", title: "Data Visualization Techniques", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "DSC350", title: "Topics in Data Science I", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "DSC354", title: "Data Warehousing and Business Intelligence", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSC270", programs: ["BSCS"] },
  { code: "DSC403", title: "Social Media Mining", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "DSC412", title: "Text Mining", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "DSC415", title: "Big Data Analytics", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "DSC306", programs: ["BSCS"] },
  { code: "DSC483", title: "Topics in Data Science II", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },

  { code: "CSC303", title: "Mobile Application Development", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSC241", programs: ["BSCS"] },
  { code: "CSC316", title: "Advance Database Systems", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSC270", programs: ["BSCS"] },
  { code: "CSC331", title: "Digital Image Processing", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "CSC336", title: "Web Technologies", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSC241", programs: ["BSCS"] },
  { code: "CSC337", title: "Advanced Web Technologies", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSC336", programs: ["BSCS"] },
  { code: "CSC353", title: "Computer Graphics", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "CSC381", title: "Blockchain Technology", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CSC412", title: "Advanced Programming", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSC241", programs: ["BSCS"] },
  { code: "CSC417", title: "E-Commerce and Digital Marketing", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSC241", programs: ["BSCS"] },
  { code: "CSC418", title: "DevOps for Cloud Computing", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "CSC441", title: "Compiler Construction", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSC312", programs: ["BSCS"] },
  { code: "CSC454", title: "Pattern Recognition", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CSC475", title: "Numerical Computing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },

  { code: "CSC334", title: "Parallel and Distributed Computing", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSC324", programs: ["BSCS", "BSSE"] },
  { code: "CSE302", title: "Software Quality Engineering", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSC291", programs: ["BSCS", "BSSE"] },
  { code: "CSE303", title: "Software Design and Architecture", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "CSC291", programs: ["BSCS", "BSSE"] },
  { code: "CSE305", title: "Software Requirement Engineering", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "CSC291", programs: ["BSCS", "BSSE"] },
  { code: "CSE307", title: "DevOps Principles and Practices", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "CSE325", title: "Software Construction and Development", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSE303", programs: ["BSCS", "BSSE"] },
  { code: "CSE326", title: "Human Computer Interaction", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CSE327", title: "Software Re-Engineering", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "CSC291", programs: ["BSCS", "BSSE"] },
  { code: "CSE337", title: "Cross-platform Application Development", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS"] },
  { code: "CSE344", title: "Green Software Engineering", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS"] },
  { code: "CSE350", title: "Topics in Software Engineering I", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CSE356", title: "Formal Methods", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "CSC291", programs: ["BSCS", "BSSE"] },
  { code: "CSE482", title: "Automated Software Testing", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CSE483", title: "Topics in Software Engineering II", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSCS", "BSSE"] },
  { code: "CSE494", title: "Software Project Management", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "CSC291", programs: ["BSCS", "BSSE"] },

  { code: "CSC494", title: "Software Project Management", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSSE"] },
  { code: "CSE300", title: "Software Metrics", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "CSC291", programs: ["BSSE"] },
  { code: "CSE333", title: "Software Process Improvement", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSSE"] },
  { code: "CSE343", title: "Agile Software Development", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSSE"] },
  { code: "CSE354", title: "Design Patterns", credit: "3(2,1)", theory: 2, lab: 1, prerequisite: "", programs: ["BSSE"] },
  { code: "CSE361", title: "Software Fault Tolerance", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["BSSE"] },

  // PhD CS Core & Electives
  { code: "PCS890", title: "Computability and Complexity Theory (Core)", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "CSC803", title: "Artificial Intelligence: Principles and Applications (Mandatory)", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MAI701", title: "Embedded Artificial Intelligence", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MAI713", title: "Generative AI", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MAI715", title: "Explainable Artificial Intelligence", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MAI723", title: "Responsible AI", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MAI727", title: "Quantum Machine Learning", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MAI730", title: "Advanced Deep Learning", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MAI732", title: "Advanced Natural Language Processing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MAI733", title: "Advanced Computer Vision", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MAI735", title: "Advanced Robotics", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MAI775", title: "Advanced Topics in Artificial Intelligence I", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MAI776", title: "Advanced Topics in Artificial Intelligence II", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCS701", title: "Advanced Wireless Networks", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCS702", title: "Advanced Wireless Sensor Networks", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCS714", title: "Mobile and Pervasive Computing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCS725", title: "Advanced Distributed Computing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCS729", title: "Internet of Things Architecture and Protocols", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCS731", title: "Challenged Networks", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCS775", title: "Advanced Topics in Computer Science I", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCS776", title: "Advanced Topics in Computer Science II", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCY701", title: "Advanced Digital Forensics and Incident Response", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCY705", title: "Advanced Network Security", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCY706", title: "Advanced Information Security", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCY710", title: "Advanced Secure Software Development", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCY712", title: "Advanced Ethical Hacking", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCY723", title: "Advanced Data Analytics for Cybersecurity", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCY775", title: "Advanced Topics in Cyber Security I", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MCY776", title: "Advanced Topics in Cyber Security II", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MDS710", title: "Advanced Data Mining", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MDS719", title: "Advanced Big Data Analytics", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MDS775", title: "Advanced Topics in Data Science I", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MDS776", title: "Advanced Topics in Data Science II", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MSE704", title: "Advanced Requirements Engineering", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MSE705", title: "Advanced Software Design and Architecture", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MSE706", title: "Advanced Software Process Improvement", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MSE707", title: "Advanced Topics in Business Process Design & Intelligence", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MSE721", title: "Advanced Human-Computer Interaction", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MSE725", title: "Advanced Software Project Management", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "MSE776", title: "Advanced Topics in Software Engineering II", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS738", title: "Special Topics in Distributed Data Processing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS780", title: "Special Topics in Multimedia Design and Technologies", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS801", title: "Special Topics in Network Programming", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS802", title: "Special Topics in Mobile and Pervasive Computing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS803", title: "Special Topics in Smart Grid Computing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS804", title: "Special Topics in Real Time Systems", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS805", title: "Special Topics in Simulation and Modeling", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS806", title: "Special Topics in Internet of Things Architecture and Protocols", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS807", title: "Special Topics in Computer Networks", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS808", title: "Special Topics in Performance Evaluation of Networks", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS809", title: "Special Topics in Ad-Hoc Networks", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS810", title: "Special Topics in Wireless Technologies", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS811", title: "Special Topics in Parallel and Distributed Systems", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS812", title: "Special Topics in Fog and Cloud Computing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS813", title: "Special Topics in High Performance Computing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS814", title: "Special Topics in Parallel Processing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS815", title: "Special Topics in Distributed Systems", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS816", title: "Special Topics in Robotics", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS817", title: "Special Topics in Human Robot Interaction", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS818", title: "Special Topics in Simultaneous Localization and Mapping", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS819", title: "Special Topics in Robotic Grasping and Fixturing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS820", title: "Special Topics in Rehabilitation and Assistive Robotics", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS821", title: "Special Topics in Agent Based Modeling", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS822", title: "Special Topics in Computer Vision and Scene Analysis", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS823", title: "Special Topics in Digital Image Processing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS824", title: "Special Topics in Knowledge Based Systems", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS825", title: "Special Topics in Machine Learning", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS826", title: "Special Topics in Deep Learning", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS827", title: "Special Topics in Reinforcement Learning", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS828", title: "Special Topics in Natural Language Processing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS829", title: "Special Topics in Information Retrieval", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS830", title: "Special Topics in Pattern Recognition", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS831", title: "Special Topics in Soft Computing Techniques", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS832", title: "Special Topics in Intelligent Systems Design", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS833", title: "Special Topics in Recommendation System", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS834", title: "Special Topics in Artificial Intelligence", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS835", title: "Special Topics in Object Oriented Databases", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS836", title: "Special Topics in Web Mining", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS837", title: "Special Topics in Stochastic Processes", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS839", title: "Special Topics in Exploratory Data Analysis & Visualization", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS840", title: "Special Topics in Big Data Analytics", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS841", title: "Special Topics in Text Mining and Analytics", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS842", title: "Special Topics in Graph Analytics for Big Data", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS843", title: "Special Topics in Social Network Analysis and Mining", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS844", title: "Special Topics in Computational Models for Social Meaning", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS845", title: "Special Topics in Time Series Analysis and Prediction", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS846", title: "Special Topics in Distributed Databases", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS847", title: "Special Topics in Data Warehousing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS848", title: "Special Topics in Data Mining", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS849", title: "Special Topics in Agile Software Development Methods", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS850", title: "Special Topics in Agent Based Software Engineering", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS851", title: "Special Topics in Software Engineering for Intelligent System", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS852", title: "Special Topics in Software Architectures for Cloud and Big Data", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS853", title: "Special Topics in Mining and Analyzing Software Repositories", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS854", title: "Special Topics in Software Project Management", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS855", title: "Special Topics in Software Estimation and Costing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS856", title: "Special Topics in Requirements Engineering", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS857", title: "Special Topics in Software Quality Assurance", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS858", title: "Special Topics in Software Engineering Technologies", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS859", title: "Special Topics in Object Oriented Software Engineering", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS860", title: "Special Topics in Software Reverse Engineering", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS861", title: "Special Topics in Software Testing", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS862", title: "Special Topics in Component Based Software", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS863", title: "Special Topics in Human Computer Interaction", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS864", title: "Special Topics in Software Engineering", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS865", title: "Special Topics in Information Security", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS866", title: "Special Topics in Information Security Management", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS867", title: "Special Topics in Cryptography", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS868", title: "Special Topics in Elliptic Curve Cryptography", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS869", title: "Special Topics in Quantum Cryptography", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS870", title: "Special Topics in Network Security", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS871", title: "Special Topics in Cyber Security", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS872", title: "Special Topics in Digital Forensics", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS873", title: "Special Topics in Privacy Preservation Techniques", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS874", title: "Special Topics in Security and Privacy for the Smart Grid", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS875", title: "Special Topics in Privacy and Security in IoT", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS876", title: "Special Topics in Secure System Design", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS877", title: "Special Topics in Cyber Threat Intelligence", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS878", title: "Special Topics in Distributed Systems Security", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS879", title: "Special Topics in Security in Cloud Environment", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS881", title: "Special Topics in Game Design and Development", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS882", title: "Special Topics in Augmented and Virtual Reality", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS883", title: "Special Topics in Computer Graphics", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS885", title: "Special Topics in Chaos Theory", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS886", title: "Special Topics in Randomized Algorithms", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS887", title: "Special Topics in Semantic Web", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS888", title: "Special Topics in Mathematical Modeling", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS889", title: "Special Topics in Estimation and Detection Theory", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS896", title: "Special Topics in Computer Science I", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS898", title: "Special Topics in Computer Science II", credit: "3(3,0)", theory: 3, lab: 0, prerequisite: "", programs: ["PhD-CS"] },
  { code: "HUM851", title: "Advanced Understanding of Holy Quran I", credit: "1(0,1)", theory: 0, lab: 1, prerequisite: "", programs: ["PhD-CS"] },
  { code: "HUM852", title: "Advanced Understanding of Holy Quran II", credit: "1(0,1)", theory: 0, lab: 1, prerequisite: "", programs: ["PhD-CS"] },
  { code: "HUM853", title: "Advanced Topics in Ethics", credit: "2(0,2)", theory: 0, lab: 2, prerequisite: "", programs: ["PhD-CS"] },
  { code: "PCS900", title: "Dissertation", credit: "9(0,9)", theory: 0, lab: 9, prerequisite: "", programs: ["PhD-CS"] }
];
